<a href="https://colab.research.google.com/github/irahanjose/Aprendizaje-de-M-quina-con-Python/blob/main/Parte0_Practica1_NoteBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **C√≥digo para el Problema del Banco**
**Decidir cu√°ndo otorgar pr√©stamos**

Hecho con üíó por alan@machinelearningenespanol.com

Los pasos para resolver el problema con Ciencia de Datos son:
1.   **Entender el problema, y establecer la decisi√≥n a automatizar.** En este caso: Decidir otorgar o no otorgar un pr√©stamo.
2.   **Recopilar datos confiables y relevantes.** Los datos se obtuvieron del repostorio p√∫blico de Machine Learning de la universidad [UCI, Irvine](https://archive.ics.uci.edu/ml/datasets/Statlog+(German+Credit+Data)).
3.   **Procesar y Limpiar los datos.** Para este ejemplo, te ayudamos con este paso. Los datos limpios se almacenaron en un archivo cvs en un repositorio de Github.
4.   **Entrenamiento del modelo.** En este Colab entrenaremos 3 modelos distintos.
5.   **Evaluaci√≥n del modelo.** En esta pr√°ctica evaluaremos los 3 modelos.
6.   **Producci√≥n.** Por lo pronto no llegaremos a este punto.
7.   **Monitoreo** Por lo pronto no llegaremos a este punto.


---


1. *Un **repositorio** es un espacio centralizado donde se almacena, organiza, mantiene y difunde informaci√≥n digital, habitualmente archivos inform√°ticos, que pueden contener trabajos cient√≠ficos, conjuntos de datos o software.*
2. *De Github recuperamos un archivo de valores separados por comas; en ingl√©s comma-separated values, por eso la extensi√≥n **.csv** . Los [archivos CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) son un tipo de documento en formato abierto sencillo para representar datos en forma de tabla.*

![](https://drive.google.com/uc?id=1zKz7y8l9yvJWGPPGUTNIIf86M1LNGB2z)


---


**NOTA:** Recuerda que el objetivo es que te familiarices con Google Colab, y que entiendas el proceso para desarrollar una soluci√≥n con Machine Learning. No te preocupes por ahora si existen algunos detalles del c√≥digo que no entiendas, pues en pr√°cticas posteriores lo veremos con mayor claridad  (‚Ä¢‚ó°‚Ä¢)‚úå


---


En este colab, solo necesitas ejecutar las celdas y observar el resultado de la ejecuci√≥n. M√°s adelante en el curso, en otras pr√°cticas, tendr√°s que escribir c√≥digo.

**Iniciemos**

Primero usaremos pandas para almacenar los datos del repositorio de Github en un dataframe. Ejecuta la siguiente celda.

In [ ]:
import pandas as pd  # Pandas ofrece estructuras de datos y operaciones para manipular tablas num√©ricas.
url = 'https://raw.githubusercontent.com/AlanCIO/Disruptora_DatasetLab0/master/CreditScoringClean.csv'
df = pd.read_csv(url) # Los datos se almacenan en un tipo de dato de pandas que se llama dataframe

Ahora los datos est√°n en un dataframe con nombre **df**. Por lo general, un dataframe usado en aprendizaje de m√°quina se ve como sigue:

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-0pky"></th>
    <th class="tg-0pky">Atributo 1</th>
    <th class="tg-0pky">Atributo 2</th>
    <th class="tg-0pky">...</th>
    <th class="tg-0pky">Atributo <span style="font-style:italic">n</span></th>
    <th class="tg-0pky">Clase</th>
  </tr>
  <tr>
    <td class="tg-0pky">0</td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
  </tr>
  <tr>
    <td class="tg-0pky">1</td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
  </tr>
  <tr>
    <td class="tg-0lax">.<br>.<br>.</td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
    <td class="tg-0lax"></td>
  </tr>
  <tr>
    <td class="tg-0pky"><span style="font-style:italic">n</span></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
    <td class="tg-c3ow"></td>
  </tr>
</table>

La primera columna indica el n√∫mero del ejemplo para entrenar; en este caso ser√≠a un cliente. Despu√©s los datos o atributos de cada cliente se ubican en columnas siguientes. Un atributo para nuestro ejemplo ser√≠a el historial crediticio del cliente. La ultima columna contiene informaci√≥n sobre la clase, es decir si se le otrog√≥ el pr√©stamo al cliente con esos atributos, o no se le otorg√≥ el pr√©stamo.


---

¬øQu√© otros atributos tenemos en el dataset? ü§î Puedes ver el contenido del dataframe ejecutando la siguiente celda. Las claves A11, A12, A30, entre otras hacen referencia al estatus del atributo.

Por ejemplo, para el atributo *CreditHistory*, la clave A30 significa que el cliente no ha solicitado un prestamo con aterioridad. Puedes ver el significado de las claves restantes en la documentaci√≥n del dataset [aqu√≠](https://archive.ics.uci.edu/ml/datasets/Statlog+(German+Credit+Data)), bajo el apartado *Attribute Information*.

In [ ]:
# Ver dataframe
df

     CheckingAcctStat A11  CheckingAcctStat A12  ...  Telephone1  CreditScore
0                       1                     0  ...           0            1
1                       0                     0  ...           1            0
2                       0                     0  ...           1            0
3                       1                     0  ...           1            1
4                       0                     0  ...           0            0
..                    ...                   ...  ...         ...          ...
945                     0                     1  ...           0            1
946                     1                     0  ...           0            1
947                     1                     0  ...           0            1
948                     1                     0  ...           0            1
949                     1                     0  ...           0            1

[950 rows x 39 columns]

LLegamos al paso relacionado con el **entrenamiento del modelo** üí™. Para este paso, usaremos [scikit-learn](https://es.wikipedia.org/wiki/Scikit-learn) (tambi√©n conocido como sklearn). Sklearn es de software libre, y contiene funciones para aprendizaje de m√°quina en Python.

Los pasos para usar un modelo y entrenarlo son:
1. Importar el modelo de sklearn
2. Crear el modelo
3. Entrenar el modelo

In [ ]:
# Usar y entrenar un modelo: √Årbol de decisi√≥n
from sklearn.tree import DecisionTreeClassifier # Importar el modelo/algoritmo de sklearn
clf = DecisionTreeClassifier()                  # Crear el modelo

¬øCu√°l es el siguiente paso? ... Exacto ‚ú®, entrenar el modelo.

In [ ]:
# Para entrenar el modelo, usaremos la funci√≥n fit. Esta funci√≥n toma dos par√°metros.
# El primero es un arreglo con los atributos, y el segundo es un arreglo con las etiquetas de las clases.

# Como nuestros datos est√°n en un dataframe que contiene tanto los atributos como las etiquetas, primero
# necesitamos separarlos en dos arreglos. Esto es f√°cil usando iloc en pandas.

# Los atributos son los valores de los ejemplos, y la etiqueta es el valor o clase que intentamos predecir
X = df.iloc[:,0:-1] # Atributos: Todas las filas, de todas las columnas exceptuando la √∫ltima
y = df.iloc[:,-1]   # Etiqueta: √öltima columna, 'CreditScore' 0: Negar pr√©stamo; 1: Asignar pr√©stamo

# Ahora s√≠ podemos entrenar el modelo con la funci√≥n fit(X,y)
clf = clf.fit(X, y)

Listo, ya tienes un modelo entrenado. Asignemos una calificaci√≥n a este modelo. En la pr√°ctica 4, hablaremos m√°s sobre la evaluaci√≥n de modelos de aprendizaje.

In [ ]:
# Evaluar el modelo: √Årbol de decisi√≥n
from sklearn.metrics import accuracy_score  
y_pred = clf.predict(X)                             # Usar los ejemplos de prueba para predecir

print('Calificaci√≥n: ', accuracy_score(y, y_pred))  # Comparar las predicciones con los valores
                                                    # reales de las etiquetas de prueba

Calificaci√≥n:  1.0

Ejecuta las siguientes celdas para entrenar y evaluar dos modelos m√°s.

In [ ]:
# Entrenar un modelo: Gaussian N√§ive Bayes
from sklearn.naive_bayes import GaussianNB  # Importar el modelo de sklearn
clf = GaussianNB()                          # Crear el modelo
clf = clf.fit(X, y)                         # Entrenar el modelo. Recuerda: En una celda anterior ya hemos
                                            # asignado a "X" los atributos, y a "y" las etiquetas de las clases

# Evaluar el modelo: Gaussian N√§ive Bayes
y_pred = clf.predict(X)                # usar los ejemplos de prueba para predecir

print('Calificaci√≥n: ', accuracy_score(y, y_pred))  # Comparar las predicciones con los valores
                                                    # reales de las etiquetas de prueba

Calificaci√≥n:  0.7347368421052631

In [ ]:
950* 0.7347368421052631

698.0

In [ ]:
# Entrenar un modelo: M√°quina de Vectores de Soporte SVM
# Equivalente a  from sklearn.svm import SVC
from sklearn import svm               # Importar el modelo de sklearn
clf = svm.SVC()                       # Crear el modelo
clf = clf.fit(X, y)                   # Entrenar el modelo

# Evaluar el modelo: M√°quina de Vectores de Soporte SVM
y_pred = clf.predict(X)          # usar los ejemplos de prueba para predecir

print('Calificaci√≥n: ', accuracy_score(y, y_pred))  # Comparar las predicciones con los valores
                                                    # reales de las etiquetas de prueba

Calificaci√≥n:  0.8578947368421053

In [ ]:
950*0.8578947368421053

815.0